<header>
    <div class="header-izquierda">
        <img src="../icons/logoBlanco.svg" alt="Logo PROA" class="logo">
    </div>

    <div class="header-derecha">
        <img src="../icons/avisos.svg" alt="Notificaciones" class="icono-notificacion">

        <button class="usuario-caja" popovertarget="menu-usuario">
            <img src="../icons/perfil.svg" alt="Icono usuario" class="icono-usuario">
            <span>José Luis</span>
        </button>
    </div>
</header>

<div id="menu-usuario" popover>
    <div>Bienvenido<br><strong>José Luis Giménez</strong></div>
    <div><a href="./logout.php">Cerrar sesión</a></div>
</div>
